list = []
a = input("Введите ваш пол: ")
list.append(a)
b = input("Введите ваше имя: ")
list.append(b)
c = int(input("Введите ваш возраст: "))
list.append(c)
d = input("Введите ваше местоположение (страна): ")
list.append(d)
e = input("Напишите различные факты о себе: ")
list.append(e)
print("Данные пользователя: ")
print("Пол: ", list[0])
print("Имя: ", list[1])
print("Возраст: ", list[2])
print("Местоположение: ", list[3])
print("Факты о человеке: ", list[4])
a = input("Желаете создать новый список? (да или нет): ")
if a == "да" or a == "Да":
    while a != "нет":
        list = []
        a = input("Введите ваш пол: ")
        list.append(a)
        b = input("Введите ваше имя: ")
        list.append(b)
        c = int(input("Введите ваш возраст: "))
        list.append(c)
        d = input("Введите ваше местоположение (страна): ")
        list.append(d)
        e = input("Напишите различные факты о себе: ")
        list.append(e)
        print("Данные пользователя: ")
        print("Пол: ", list[0])
        print("Имя: ", list[1])
        print("Возраст: ", list[2])
        print("Местоположение: ", list[3])
        print("Факты о человеке: ", list[4])
        a = input("Желаете создать новый список? (да или нет): ")
elif a == "нет" or a == "Нет":
    print("Программа завершена")
else:
    print("Введены неверные данные")
